# Generated by Django 3.1.4 on 2020-12-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_category_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descripshion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='prace',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='viziboll',
            field=models.BooleanField(default=True),
        ),
    ]
