# Generated by Django 3.1.4 on 2020-12-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20201217_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descripshion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
