# Generated by Django 3.1.4 on 2020-12-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='all_category',
            field=models.ManyToManyField(related_name='all_category', to='article.Category'),
        ),
    ]
