# Generated by Django 3.1.5 on 2021-01-23 19:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0010_auto_20210123_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Present',
            new_name='Presents',
        ),
    ]
