# Generated by Django 3.1 on 2021-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20210123_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='logo'),
        ),
    ]
