# Generated by Django 3.1 on 2021-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_article_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='logo_height',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='logo_width',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
