# Generated by Django 3.1 on 2021-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20210204_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='logo_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='logo_width',
            field=models.IntegerField(default=0),
        ),
    ]
