# Generated by Django 3.1 on 2021-03-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphone', models.CharField(max_length=200)),
                ('mail', models.TextField(blank=True, null=True)),
                ('skype', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('residence_address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
