# Generated by Django 3.1 on 2021-03-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='residence_address',
            new_name='address',
        ),
    ]
