# Generated by Django 3.1 on 2021-02-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='productshop',
            name='logo_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productshop',
            name='logo_width',
            field=models.IntegerField(default=0),
        ),
    ]
