# Generated by Django 3.1 on 2021-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementinformation',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
