# Generated by Django 3.1 on 2021-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20210204_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementinformation',
            name='logo_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elementinformation',
            name='logo_width',
            field=models.IntegerField(default=0),
        ),
    ]
