# Generated by Django 3.1 on 2021-02-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='prace',
            new_name='iphone',
        ),
    ]
