# Generated by Django 3.1 on 2021-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210215_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='iphone',
            field=models.CharField(max_length=200),
        ),
    ]
