# Generated by Django 3.1 on 2021-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210228_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementorder',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='elementorder',
            name='logo_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elementorder',
            name='logo_width',
            field=models.IntegerField(default=0),
        ),
    ]
