# Generated by Django 3.1 on 2021-03-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210214_1154'),
        ('order', '0009_auto_20210228_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productshop'),
        ),
    ]
